#!/bin/bash
# note: keep in sync with ci.yml

test -x ./cargofixall || exit 3

echo "Run Cargo Fmt+Clippy Fix ...."


cargo fix

./cargo-nightly fmt --all
#cargo +nightly fmt --all

#cargo clippy --fix --all-targets -- -D warnings
 ./cargo-nightly clippy --fix -Zunstable-options --workspace --all-targets --all-features -- --deny=warnings

